package im.tox.tox4j.crypto

object ToxCryptoConstants {
    const val ENCRYPTION_EXTRA_LENGTH = 80

    /** The number of bytes in a hash generated by [hash]. */
    const val HASH_LENGTH = 32

    const val KEY_LENGTH = 32

    const val SALT_LENGTH = 32

    const val PUBLIC_KEY_LENGTH = 32
    const val SECRET_KEY_LENGTH = 32
    const val SHARED_KEY_LENGTH = 32
    const val NONCE_LENGTH = 24

    const val ZERO_BYTES = 32
    const val BOX_ZERO_BYTES = 16
}
