package im.tox.tox4j.impl.jni;

import im.tox.tox4j.core.exceptions.ToxBootstrapException;
import im.tox.tox4j.core.exceptions.ToxConferenceByIdException;
import im.tox.tox4j.core.exceptions.ToxConferenceDeleteException;
import im.tox.tox4j.core.exceptions.ToxConferenceGetIdException;
import im.tox.tox4j.core.exceptions.ToxConferenceGetTypeException;
import im.tox.tox4j.core.exceptions.ToxConferenceInviteException;
import im.tox.tox4j.core.exceptions.ToxConferenceJoinException;
import im.tox.tox4j.core.exceptions.ToxConferenceNewException;
import im.tox.tox4j.core.exceptions.ToxConferencePeerQueryException;
import im.tox.tox4j.core.exceptions.ToxConferenceSendMessageException;
import im.tox.tox4j.core.exceptions.ToxConferenceSetMaxOfflineException;
import im.tox.tox4j.core.exceptions.ToxConferenceTitleException;
import im.tox.tox4j.core.exceptions.ToxFileControlException;
import im.tox.tox4j.core.exceptions.ToxFileGetException;
import im.tox.tox4j.core.exceptions.ToxFileSeekException;
import im.tox.tox4j.core.exceptions.ToxFileSendChunkException;
import im.tox.tox4j.core.exceptions.ToxFileSendException;
import im.tox.tox4j.core.exceptions.ToxFriendAddException;
import im.tox.tox4j.core.exceptions.ToxFriendByPublicKeyException;
import im.tox.tox4j.core.exceptions.ToxFriendCustomPacketException;
import im.tox.tox4j.core.exceptions.ToxFriendDeleteException;
import im.tox.tox4j.core.exceptions.ToxFriendGetLastOnlineException;
import im.tox.tox4j.core.exceptions.ToxFriendGetPublicKeyException;
import im.tox.tox4j.core.exceptions.ToxFriendQueryException;
import im.tox.tox4j.core.exceptions.ToxFriendSendMessageException;
import im.tox.tox4j.core.exceptions.ToxGetPortException;
import im.tox.tox4j.core.exceptions.ToxGroupDisconnectException;
import im.tox.tox4j.core.exceptions.ToxGroupInviteAcceptException;
import im.tox.tox4j.core.exceptions.ToxGroupInviteFriendException;
import im.tox.tox4j.core.exceptions.ToxGroupIsConnectedException;
import im.tox.tox4j.core.exceptions.ToxGroupJoinException;
import im.tox.tox4j.core.exceptions.ToxGroupKickPeerException;
import im.tox.tox4j.core.exceptions.ToxGroupLeaveException;
import im.tox.tox4j.core.exceptions.ToxGroupNewException;
import im.tox.tox4j.core.exceptions.ToxGroupPeerQueryException;
import im.tox.tox4j.core.exceptions.ToxGroupSelfNameSetException;
import im.tox.tox4j.core.exceptions.ToxGroupSelfQueryException;
import im.tox.tox4j.core.exceptions.ToxGroupSelfStatusSetException;
import im.tox.tox4j.core.exceptions.ToxGroupSendCustomPacketException;
import im.tox.tox4j.core.exceptions.ToxGroupSendCustomPrivatePacketException;
import im.tox.tox4j.core.exceptions.ToxGroupSendMessageException;
import im.tox.tox4j.core.exceptions.ToxGroupSendPrivateMessageException;
import im.tox.tox4j.core.exceptions.ToxGroupSetIgnoreException;
import im.tox.tox4j.core.exceptions.ToxGroupSetPasswordException;
import im.tox.tox4j.core.exceptions.ToxGroupSetPeerLimitException;
import im.tox.tox4j.core.exceptions.ToxGroupSetPrivacyStateException;
import im.tox.tox4j.core.exceptions.ToxGroupSetRoleException;
import im.tox.tox4j.core.exceptions.ToxGroupSetTopicLockException;
import im.tox.tox4j.core.exceptions.ToxGroupSetVoiceStateException;
import im.tox.tox4j.core.exceptions.ToxGroupStateQueryException;
import im.tox.tox4j.core.exceptions.ToxGroupTopicSetException;
import im.tox.tox4j.core.exceptions.ToxNewException;
import im.tox.tox4j.core.exceptions.ToxSetInfoException;
import im.tox.tox4j.core.exceptions.ToxSetTypingException;

@SuppressWarnings({"checkstyle:emptylineseparator", "checkstyle:linelength"})
public final class ToxCoreJni {
    static {
      System.loadLibrary("tox4j-c");
    }

    static native int toxConferenceNew(int instanceNumber) throws ToxConferenceNewException;
    static native void toxConferenceDelete(int instanceNumber, int conferenceNumber) throws ToxConferenceDeleteException;
    static native int toxConferencePeerCount(int instanceNumber, int conferenceNumber) throws ToxConferencePeerQueryException;
    static native int toxConferenceOfflinePeerCount(int instanceNumber, int conferenceNumber) throws ToxConferencePeerQueryException;
    static native void toxConferenceSetMaxOffline(int instanceNumber, int conferenceNumber, int maxOffline) throws ToxConferenceSetMaxOfflineException;
    static native int toxConferenceJoin(int instanceNumber, int friendNumber, byte[] cookie) throws ToxConferenceJoinException;
    static native void toxConferenceSendMessage(int instanceNumber, int conferenceNumber, int type, byte[] message) throws ToxConferenceSendMessageException;
    static native byte[] toxConferenceGetTitle(int instanceNumber, int conferenceNumber) throws ToxConferenceTitleException;
    static native void toxConferenceSetTitle(int instanceNumber, int conferenceNumber, byte[] title) throws ToxConferenceTitleException;
    static native int toxConferenceGetType(int instanceNumber, int conferenceNumber) throws ToxConferenceGetTypeException;
    static native byte[] toxConferenceGetId(int instanceNumber, int conferenceNumber) throws ToxConferenceGetIdException;
    static native int toxConferenceById(int instanceNumber, byte[] id) throws ToxConferenceByIdException;
    static native byte[] toxConferenceOfflinePeerGetName(int instanceNumber, int conferenceNumber, int offlinePeerNumber) throws ToxConferencePeerQueryException;
    static native byte[] toxConferenceOfflinePeerGetPublicKey(int instanceNumber, int conferenceNumber, int offlinePeerNumber) throws ToxConferencePeerQueryException;
    static native long toxConferenceOfflinePeerGetLastActive(int instanceNumber, int conferenceNumber, int offlinePeerNumber) throws ToxConferencePeerQueryException;
    static native byte[] toxConferencePeerGetName(int instanceNumber, int conferenceNumber, int peerNumber) throws ToxConferencePeerQueryException;
    static native byte[] toxConferencePeerGetPublicKey(int instanceNumber, int conferenceNumber, int peerNumber) throws ToxConferencePeerQueryException;
    static native boolean toxConferencePeerNumberIsOurs(int instanceNumber, int conferenceNumber, int peerNumber) throws ToxConferencePeerQueryException;
    static native int toxFileSend(int instanceNumber, int friendNumber, int kind, long fileSize, byte[] fileId, byte[] filename) throws ToxFileSendException;
    static native int toxFriendAdd(int instanceNumber, byte[] address, byte[] message) throws ToxFriendAddException;
    static native int toxFriendAddNorequest(int instanceNumber, byte[] publicKey) throws ToxFriendAddException;
    static native void toxFriendDelete(int instanceNumber, int friendNumber) throws ToxFriendDeleteException;
    static native int toxFriendByPublicKey(int instanceNumber, byte[] publicKey) throws ToxFriendByPublicKeyException;
    static native boolean toxFriendExists(int instanceNumber, int friendNumber);
    static native byte[] toxFriendGetPublicKey(int instanceNumber, int friendNumber) throws ToxFriendGetPublicKeyException;
    static native long toxFriendGetLastOnline(int instanceNumber, int friendNumber) throws ToxFriendGetLastOnlineException;
    static native boolean toxFriendGetTyping(int instanceNumber, int friendNumber) throws ToxFriendQueryException;
    static native int toxFriendSendMessage(int instanceNumber, int friendNumber, int type, byte[] message) throws ToxFriendSendMessageException;
    static native void toxFriendSendLossyPacket(int instanceNumber, int friendNumber, byte[] data) throws ToxFriendCustomPacketException;
    static native void toxFriendSendLosslessPacket(int instanceNumber, int friendNumber, byte[] data) throws ToxFriendCustomPacketException;
    static native int toxGroupNew(int instanceNumber, int privacyState, byte[] groupName, byte[] name) throws ToxGroupNewException;
    static native int toxGroupJoin(int instanceNumber, byte[] chatId, byte[] name, byte[] password) throws ToxGroupJoinException;
    static native boolean toxGroupIsConnected(int instanceNumber, int groupNumber) throws ToxGroupIsConnectedException;
    static native void toxGroupDisconnect(int instanceNumber, int groupNumber) throws ToxGroupDisconnectException;
    static native void toxGroupLeave(int instanceNumber, int groupNumber, byte[] partMessage) throws ToxGroupLeaveException;
    static native void toxGroupSelfSetName(int instanceNumber, int groupNumber, byte[] name) throws ToxGroupSelfNameSetException;
    static native byte[] toxGroupSelfGetName(int instanceNumber, int groupNumber) throws ToxGroupSelfQueryException;
    static native void toxGroupSelfSetStatus(int instanceNumber, int groupNumber, int status) throws ToxGroupSelfStatusSetException;
    static native int toxGroupSelfGetStatus(int instanceNumber, int groupNumber) throws ToxGroupSelfQueryException;
    static native int toxGroupSelfGetRole(int instanceNumber, int groupNumber) throws ToxGroupSelfQueryException;
    static native int toxGroupSelfGetPeerId(int instanceNumber, int groupNumber) throws ToxGroupSelfQueryException;
    static native byte[] toxGroupSelfGetPublicKey(int instanceNumber, int groupNumber) throws ToxGroupSelfQueryException;
    static native void toxGroupSetTopic(int instanceNumber, int groupNumber, byte[] topic) throws ToxGroupTopicSetException;
    static native byte[] toxGroupGetTopic(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native byte[] toxGroupGetName(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native byte[] toxGroupGetChatId(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native int toxGroupGetPrivacyState(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native int toxGroupGetVoiceState(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native int toxGroupGetTopicLock(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native int toxGroupGetPeerLimit(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native byte[] toxGroupGetPassword(int instanceNumber, int groupNumber) throws ToxGroupStateQueryException;
    static native int toxGroupSendMessage(int instanceNumber, int groupNumber, int messageType, byte[] message) throws ToxGroupSendMessageException;
    static native int toxGroupSendPrivateMessage(int instanceNumber, int groupNumber, int peerId, int messageType, byte[] message) throws ToxGroupSendPrivateMessageException;
    static native void toxGroupSendCustomPacket(int instanceNumber, int groupNumber, boolean lossless, byte[] data) throws ToxGroupSendCustomPacketException;
    static native void toxGroupSendCustomPrivatePacket(int instanceNumber, int groupNumber, int peerId, boolean lossless, byte[] data) throws ToxGroupSendCustomPrivatePacketException;
    static native void toxGroupInviteFriend(int instanceNumber, int groupNumber, int friendNumber) throws ToxGroupInviteFriendException;
    static native int toxGroupInviteAccept(int instanceNumber, int friendNumber, byte[] inviteData, byte[] name, byte[] password) throws ToxGroupInviteAcceptException;
    static native void toxGroupSetPassword(int instanceNumber, int groupNumber, byte[] password) throws ToxGroupSetPasswordException;
    static native void toxGroupSetTopicLock(int instanceNumber, int groupNumber, int topicLock) throws ToxGroupSetTopicLockException;
    static native void toxGroupSetVoiceState(int instanceNumber, int groupNumber, int voiceState) throws ToxGroupSetVoiceStateException;
    static native void toxGroupSetPrivacyState(int instanceNumber, int groupNumber, int privacyState) throws ToxGroupSetPrivacyStateException;
    static native void toxGroupSetPeerLimit(int instanceNumber, int groupNumber, int peerLimit) throws ToxGroupSetPeerLimitException;
    static native void toxGroupSetIgnore(int instanceNumber, int groupNumber, int peerId, boolean ignore) throws ToxGroupSetIgnoreException;
    static native void toxGroupSetRole(int instanceNumber, int groupNumber, int peerId, int role) throws ToxGroupSetRoleException;
    static native void toxGroupKickPeer(int instanceNumber, int groupNumber, int peerId) throws ToxGroupKickPeerException;
    static native byte[] toxGroupPeerGetName(int instanceNumber, int groupNumber, int peerNumber) throws ToxGroupPeerQueryException;
    static native int toxGroupPeerGetStatus(int instanceNumber, int groupNumber, int peerNumber) throws ToxGroupPeerQueryException;
    static native int toxGroupPeerGetRole(int instanceNumber, int groupNumber, int peerNumber) throws ToxGroupPeerQueryException;
    static native int toxGroupPeerGetConnectionStatus(int instanceNumber, int groupNumber, int peerNumber) throws ToxGroupPeerQueryException;
    static native byte[] toxGroupPeerGetPublicKey(int instanceNumber, int groupNumber, int peerNumber) throws ToxGroupPeerQueryException;
    static native int toxNew(byte[] options) throws ToxNewException;
    static native void toxKill(int instanceNumber);
    static native byte[] toxGetSavedata(int instanceNumber);
    static native void toxBootstrap(int instanceNumber, String host, int port, byte[] publicKey) throws ToxBootstrapException;
    static native void toxAddTcpRelay(int instanceNumber, String host, int port, byte[] publicKey) throws ToxBootstrapException;
    static native int toxIterationInterval(int instanceNumber);
    static native byte[] toxIterate(int instanceNumber);
    static native byte[] toxSelfGetAddress(int instanceNumber);
    static native void toxSelfSetNospam(int instanceNumber, int nospam);
    static native int toxSelfGetNospam(int instanceNumber);
    static native byte[] toxSelfGetPublicKey(int instanceNumber);
    static native byte[] toxSelfGetSecretKey(int instanceNumber);
    static native void toxSelfSetName(int instanceNumber, byte[] name) throws ToxSetInfoException;
    static native byte[] toxSelfGetName(int instanceNumber);
    static native void toxSelfSetStatusMessage(int instanceNumber, byte[] statusMessage) throws ToxSetInfoException;
    static native byte[] toxSelfGetStatusMessage(int instanceNumber);
    static native void toxSelfSetStatus(int instanceNumber, int status);
    static native int toxSelfGetStatus(int instanceNumber);
    static native int[] toxSelfGetFriendList(int instanceNumber);
    static native void toxSelfSetTyping(int instanceNumber, int friendNumber, boolean typing) throws ToxSetTypingException;
    static native void toxFileControl(int instanceNumber, int friendNumber, int fileNumber, int control) throws ToxFileControlException;
    static native void toxFileSeek(int instanceNumber, int friendNumber, int fileNumber, long position) throws ToxFileSeekException;
    static native byte[] toxFileGetFileId(int instanceNumber, int friendNumber, int fileNumber) throws ToxFileGetException;
    static native void toxFileSendChunk(int instanceNumber, int friendNumber, int fileNumber, long position, byte[] data) throws ToxFileSendChunkException;
    static native void toxConferenceInvite(int instanceNumber, int friendNumber, int conferenceNumber) throws ToxConferenceInviteException;
    static native int[] toxConferenceGetChatlist(int instanceNumber);
    static native byte[] toxSelfGetDhtId(int instanceNumber);
    static native int toxSelfGetUdpPort(int instanceNumber) throws ToxGetPortException;
    static native int toxSelfGetTcpPort(int instanceNumber) throws ToxGetPortException;
    static native void toxFinalize(int instanceNumber);
}
